name: 'CD'

on:
  pull_request:
    branches:
      - test
      - prod
    types:
      - closed

jobs:
  build_and_push_image:
    if: github.event.pull_request.merged == true
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was successfully merged ${{vars.ENV_VARSS}} is the env var
