name: 'CD'

on:
  push:
    branches:
      - test
      - prod
jobs:
  build_and_push_image:

    environment:
      name: ${{github.event.pull_request.base.ref}}

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        id: checkout

      - name: current Branch
        run: |
          echo ${{github.event.pull_request.base.ref}}

      - name: verbose
        run: |
          echo ${{github.event.pull_request.base.ref}}
          echo The PR was successfully merged ${{vars.ENV_VARS}} is the env var
