name: 'CD'

on:
  pull_request:
    branches:
      - test
      - prod
    types:
      - closed

jobs:
  build_and_push_image:
    if: github.event.pull_request.merged == true
    environment:
      name: ${{github.event.pull_request.base.ref}}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{github.event.pull_request.base.ref}}
        echo The PR was successfully merged ${{vars.ENV_VARS}} is the env var
