name: 'CD'

on:
  pull_request:
    branches:
      - test
      - prod
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was successfully merged.