name: 'CI: Build and Test'

on:
  push:
    branches:
      - feature/**
jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        id: checkout

      - name: current Branch
        run: |
          echo ${{ github.ref_name }}
  
      - name: build and testing
        if: 
        run: |
<<<<<<< HEAD
          echo build and testing
=======
          echo build and testing and another test1123
>>>>>>> c6c0c1fa86c38921bcee0d45fe047e0f17c8c2bb
