name: 'CI: build and publish'

on:
  push:
    branches:
      - test
      - prod
jobs:
  build_and_push_image:

    environment:
      name: ${{ github.ref_name }}

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        id: checkout

      - name: current Branch
        run: |
          echo ${{ github.ref_name }}

      - name: verbose
        run: |
          echo ${{ github.ref_name }}
          echo The PR was successfully merged ${{vars.ENV_VARS}} is the env var
