name: 'CI'

on:
  pull_request:

  
    
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: ${{ ( github.event.pull_request.base.ref == 'prod' && github.event.pull_request.head.ref != 'test' ) || ( github.event.pull_request.base.ref == 'test' && (startsWith(github.event.pull_request.head.ref, 'feature/') != true) ) }}
        run: |
          echo "${{github.event.pull_request.head.ref}}" 
          echo test
          exit 1


  build:
    runs-on: ubuntu-latest
    needs: check_branch
    steps:
      - name: build and testing
        if: 
        run: |
          echo build and testing