name: 'CI'

on:
  pull_request:
    types: [opened, edited, closed, reopened, assigned, unassigned, review_requested, review_request_removed, labeled, unlabeled, synchronize]
    
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: ${{ ( github.event.pull_request.base.ref == 'prod' && github.event.pull_request.head.ref != 'test' ) || ( github.event.pull_request.base.ref == 'test' && (startsWith(github.event.pull_request.head.ref, 'feature/') != true) ) }}
        run: |
          echo "${{github.event.pull_request.head.ref}}" 
          exit 1

  build_and_test:
    runs-on: ubuntu-latest
    needs: check_branch
    steps:
      - name: checkout
        uses: actions/checkout@v3
        id: checkout

      - name: current Branch
        run: |
          git rev-parse --abbrev-ref HEAD
  
      - name: build and testing
        if: 
        run: |
          echo build and testing