name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: (github.event.pull_request.base.ref == 'prod' && github.event.pull_request.head.ref != 'test') || (github.event.pull_request.base.ref == 'test' && startsWith(github.event.pull_request.head.ref, 'feature'))
        run: |
          echo echo $github.event.pull_request.head.ref
          exit 1