name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: (github.base_ref == 'prod' && github.head_ref != 'test') || (github.base_ref == 'test' && contains(github.head_ref, 'feature'))
        run: |
          echo "ERROR: You can only merge to main from dev."
          exit 1