name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: ${{ startsWith(github.event.pull_request.head.ref, 'feature') }}
        run: |
          echo "${{github.event.pull_request.head.ref}}"
          exit 1